// react/src/index.ts
import React, { useState, useEffect } from "react";
import { css, CSSProperties } from "@stitches/core";

// Используем Map для хранения стилей по их идентификаторам.
const stylesMap = new Map<string, CSSProperties>();

type StyledHookReturnType = {
  className: string;
  selector: string;
  props: {};
};

const createStyledHook = <T extends Record<string, unknown>>(cssFunction: typeof css, cssParams: (props: T) => CSSProperties) => {
  const useStyled = (props: T): StyledHookReturnType => {
    const [ styleSignal, setStyleSignal ] = useState(() => cssFunction({})());

    useEffect(() => {
      const style = cssFunction(cssParams(props) as { [name: string]: unknown; });
      if (stylesMap.has(style.className)) {
        stylesMap.set(style.className, cssParams(props));
      } else {
        stylesMap.set(style.className, cssParams(props));
      }
      setStyleSignal(style());
    }, [props]);

    return styleSignal;
  };

  return useStyled;
};

export { createStyledHook };

// solid/src/index.ts
/* eslint-disable @typescript-eslint/ban-types */
import { css, CSSProperties } from "@stitches/core";
import { Accessor, createEffect, createSignal } from "solid-js";

// Use a map to store created styles for quick access and replacement
const stylesMap: Map<string, CSSRule> = new Map();

export function createStyledHook<T extends Record<string, unknown>>(cssf: typeof css, cssParams: (props: T) => CSSProperties) {
	return function useStyled(props: T): Accessor<string & {
		className: string;
		selector: string;
		props: {};
	}> {
		const [styleSignal, setStyleSignal] = createSignal(cssf({})());

		createEffect(() => {
			const style = cssf({
				...cssParams(props),
			});

			const existingStyle = stylesMap.get(style.className);
			if (existingStyle)
				existingStyle.deleteRule(existingStyle.selectorText);

			style.insertRule(style.cssText);

			stylesMap.set(style.className, style);

			setStyleSignal(style());
		});

		return styleSignal;
	};
}
